### PR TITLE
Update readme with prereqs

### PR DESCRIPTION
**Pull request by figadore**
feel free to modify as needed, just thought other uart beginners like me could use a bit more hand holding to go from 0 to sensing

### CODE REVIEW

**Comment by Arya11111** [comment]
Sorry ，You can check the wiki tutorial：
https://wiki.dfrobot.com/_A02YYUW_Waterproof_Ultrasonic_Sensor_SKU_SEN0311
https://img.dfrobot.com.cn/wiki/none/596e01f35a3c08d554d3412253e33e3c
Hope it will help you.

**Comment by figadore** [comment]
how about a link to the wiki in the readme then? usually developers expect to find everything they need to get started with a project either in the readme, or linked from the readme

**Comment by Arya11111** [comment]
All our libraries have added product links, which can jump directly to wiki links.  You can click the 【product link】 in the readme file, which will detail how to use the product.  Hope it will help you.

**Comment by gjanssens** [comment]
> Sorry ，You can check the wiki tutorial： https://wiki.dfrobot.com/_A02YYUW_Waterproof_Ultrasonic_Sensor_SKU_SEN0311 https://img.dfrobot.com.cn/wiki/none/596e01f35a3c08d554d3412253e33e3c Hope it will help you.

Is there an English translation available of the document in the second link ?

**Comment by Arya11111** [comment]
Sorry，there is no English document, but this does not affect your use.
________________________________
发件人: Geert Janssens ***@***.***>
发送时间: 2022年12月12日 1:36
收件人: DFRobot/DFRobot_RaspberryPi_A02YYUW ***@***.***>
抄送: 彭雪 ***@***.***>; State change ***@***.***>
主题: Re: [DFRobot/DFRobot_RaspberryPi_A02YYUW] Update readme with prereqs (PR #2)


Sorry ，You can check the wiki tutorial： https://wiki.dfrobot.com/_A02YYUW_Waterproof_Ultrasonic_Sensor_SKU_SEN0311 https://img.dfrobot.com.cn/wiki/none/596e01f35a3c08d554d3412253e33e3c Hope it will help you.

Is there an English translation available of the document in the second link ?

―

**Pull request closed without merging**
